# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version 

Vagrant.configure(2) do |config|

  config.vm.box = "box-cutter/ubuntu1404-desktop"

  config.vm.hostname = "Vagrant-mverma4-PSPWizard"

   config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
      vb.gui = true
      vb.memory = "1024"
      vb.name = "Vagrant-mverma4-PSPWizard"
    end
  
  # Enable provisioning with a shell script. 
    config.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y openjdk-7-jdk
    SHELL
end
