# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version 
Vagrant.configure(2) do |config|
  
  #Configures the vm box
  config.vm.box = "nritholtz/ubuntu-14.04.1"
  
  #Configures the vm hostname
  config.vm.hostname = "Onslow-mverma4-PSPWizard-Vagrant"
   
   config.vm.provider "virtualbox" do |vb|
     
      # Display the VirtualBox GUI when booting the machine
      vb.gui = true
      
      # Sets the Vm memory
      vb.memory = "1024"
      
      # sets the vm name
      vb.name = "Onslow-mverma4-PSPWizard-Vagrant"
      
      #Disable USB
      vb.customize ["modifyvm", :id, "--usb", "off"]
      vb.customize ["modifyvm", :id, "--usbehci", "off"]
    
    end
  
  # Enable provisioning with a shell script. 
    config.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      
      # install jdk
      sudo apt-get install -y openjdk-7-jdk 
      
      cd /home/vagrant/Desktop
      # download from github repository
      sudo wget https://codeload.github.com/SoftwareEngineeringToolDemos/FSE-2011-PSPWizard/zip/master
      
      # moving the files to destop and setting permissions
       unzip master
        sudo chmod -R 777 /home/vagrant/Desktop/FSE-2011-PSPWizard-master
        mv /home/vagrant/Desktop/FSE-2011-PSPWizard-master/* /home/vagrant/Desktop
        rm -rf master
        rm -rf FSE-2011-PSPWizard-master
        rm -rf README.*
        mv /home/vagrant/Desktop/build_vm/VM_Essentials/* /home/vagrant/Desktop
        rm -rf build_vm
        mv "/home/vagrant/Desktop/PSPWizard Bin/bin/PSPWizard.jar" /home/vagrant/Desktop
       
        # to make the tool run at startup
        cd /home/vagrant/.config
        mkdir autostart
        mv /home/vagrant/Desktop/PSPWizard.desktop /home/vagrant/.config/autostart
       
        # reboot to make changes
        sudo reboot
    SHELL
end
